
INSERT INTO admin (name, password) VALUES
('admin', '1234');

INSERT INTO product (name, description, photo, thumbnail, price, category, subcategory, stock) VALUES
('FOND DE CAVE', 'VINO TINTO CABERNET RESERVA FOND DE CAVE X 750 CC', '/photos/fond_de_cave.jpg', '/thumbnails/fond_de_cave.jpg', 13295.0, 'VINO', 'TINTO', 30),
('DON DAVID', 'VINO TINTO MALBEC RESERVA DON DAVID X 750 CC', '/photos/don_david.jpg', '/thumbnails/don_david.jpg', 13295.0, 'VINO', 'TINTO', 30),
('PAZ', 'VINO TINTO SYRAH PAZ X 750 CC', '/photos/paz.jpg', '/thumbnails/paz.jpg', 13295.0, 'VINO', 'TINTO', 30),
('LOS HELECHOS', 'VINO TINTO MALBEC LOS HELECHOS RESERVA X 750 CC', '/photos/los_helechos.jpg', '/thumbnails/los_helechos.jpg', 13284.0, 'VINO', 'TINTO', 30),
('FABRE MONTMAYOU', 'VINO TINTO CABERNET FRANC FABRE MONTMAYOU X 750 CC', '/photos/fabre_montmayou.jpg', '/thumbnails/fabre_montmayou.jpg', 13230.0, 'VINO', 'TINTO', 30),
('PORTILLO', 'VINO TINTO MALBEC MAGNUM PORTILLO X 1.5 LT', '/photos/portillo.jpg', '/thumbnails/portillo.jpg', 13199.0, 'VINO', 'TINTO', 30),
('PYROS', 'VINO TINTO MALBEC CABERNET PEDERNAL VALLEY PYROS X', '/photos/pyros.jpg', '/thumbnails/pyros.jpg', 13100.0, 'VINO', 'TINTO', 30),
('OJO DE BUEN CUBERO', 'VINO TINTO MALBEC OJO DE BUEN CUBERO X 750 CC', '/photos/ojo_de_buen_cubero.jpg', '/thumbnails/ojo_de_buen_cubero.jpg', 13095.0, 'VINO', 'TINTO', 30),
('SAINT FELICIEN', 'VINO TINTO MALBEC SAINT FELICIEN X 750 CC', '/photos/saint_felicien.jpg', '/thumbnails/saint_felicien.jpg', 12992.0, 'VINO', 'TINTO', 30),
('GRAN ALAMBRADO', 'VINO TINTO MALB CAB SAUV GRAN ALAMBRADO X 750 CC', '/photos/gran_alambrado.jpg', '/thumbnails/gran_alambrado.jpg', 12879.0, 'VINO', 'TINTO', 30),
('SALENTEIN', 'VINO ROSADO RESERVA SALENTEIN X 750 CC', '/photos/salentein.jpg', '/thumbnails/salentein.jpg', 12600.0, 'VINO', 'ROSADO', 30),
('LAS PERDICES', 'VINO ROSADO MALBEC LAS PERDICES BOTELLA X750CC', '/photos/las_perdices.jpg', '/thumbnails/las_perdices.jpg', 11669.0, 'VINO', 'ROSADO', 30),
('NINA', 'VINO ROSADO MALBEC TARDIO NINA BOT X 750 CC', '/photos/nina.jpg', '/thumbnails/nina.jpg', 10609.0, 'VINO', 'ROSADO', 30),
('VINO ARTESANO', 'VINO ROSADO ORGANICO ARTESANO DE ARGENTO X 750CC', '/photos/vino_artesano.jpg', '/thumbnails/vino_artesano.jpg', 10412.87, 'VINO', 'ROSADO', 30),
('UXMAL', 'VINO ROSADO UXMAL X 750 CC', '/photos/uxmal.jpg', '/thumbnails/uxmal.jpg', 7700.0, 'VINO', 'ROSADO', 30),
('LOS INTOCABLES', 'VINO BLANCO CHARDONNAY LOS INTOCABLES X 750 CC', '/photos/los_intocables.jpg', '/thumbnails/los_intocables.jpg', 12160.0, 'VINO', 'BLANCO', 30),
('NICASIA', 'VINO BLANCO BLANC DE BLAN NICASIA X 750 CC', '/photos/nicasia.jpg', '/thumbnails/nicasia.jpg', 11969.0, 'VINO', 'BLANCO', 30),
('SOMBRERO', 'VINO BLANCO SAVIGNON BLANC SOMBRERO BOT X 750 CC', '/photos/sombrero.jpg', '/thumbnails/sombrero.jpg', 11445.0, 'VINO', 'BLANCO', 30),
('AMALAYA', 'VINO BLANCO BLEND AMALAYA X 750 CC', '/photos/amalaya.jpg', '/thumbnails/amalaya.jpg', 10639.0, 'VINO', 'BLANCO', 30),
('NORTON', 'VINO BLANCO CHARDONNAY RESERVA NORTON BOT X 750 CC', '/photos/norton.jpg', '/thumbnails/norton.jpg', 10150.0, 'VINO', 'BLANCO', 30),
('BARON B', 'VINO ESPUMANTE BRUT NATURE BARON B X 750 CC', '/photos/baron_b.jpg', '/thumbnails/baron_b.jpg', 41849.0, 'VINO', 'ESPUMANTE', 30),
('CHANDON', 'VINO ESPUMANTE EXTRA BRUT EST MAGNUM CHANDON X1500CC', '/photos/chandon.jpg', '/thumbnails/chandon.jpg', 39570.0, 'VINO', 'ESPUMANTE', 30),
('LA POSTA', 'VINO ESPUMANTE NATURE LA POSTA BOT X 750 CC', '/photos/la_posta.jpg', '/thumbnails/la_posta.jpg', 26050.0, 'VINO', 'ESPUMANTE', 30),
('ALYDA', 'VINO ESPUMANTE BRUT ROSE ALYDA X 750 CC', '/photos/alyda.jpg', '/thumbnails/alyda.jpg', 25300.0, 'VINO', 'ESPUMANTE', 30),
('LUIGI BOSCA', 'VINO ESPUMANTE EXTRA BRUT LUIGI BOSCA X 750 CC', '/photos/luigi_bosca.jpg', '/thumbnails/luigi_bosca.jpg', 22429.0, 'VINO', 'ESPUMANTE', 30),
('ILLY', 'CAFE GRANO TOSTADO ILLY LATA X 250 GRS', '/photos/illy.jpg', '/thumbnails/illy.jpg', 27800.0, 'CAFE', 'GRANO', 30),
('CABRALES', 'CAFE MOLIDO TOSTADO SUPER CABRALES X 500 GRS', '/photos/cabrales.jpg', '/thumbnails/cabrales.jpg', 27069.0, 'CAFE', 'MOLIDO', 30),
('MORENITA', 'CAFE EGRANO TOSTADO COLOMBIA MORENITA X 500 GRS', '/photos/morenita.jpg', '/thumbnails/morenita.jpg', 26100.0, 'CAFE', 'EGRANO', 30),
('NESCAFE', 'CAFE INSTANTANEO EXPRESSO GOLD NESCAFE X 100 GRS', '/photos/nescafe.jpg', '/thumbnails/nescafe.jpg', 25659.0, 'CAFE', 'INSTANTANEO', 30),
('SENSACIONES', 'CAFE MOLIDO INTENSO SENSACIONES BONAFIDE X 1KG', '/photos/sensaciones.jpg', '/thumbnails/sensaciones.jpg', 25450.0, 'CAFE', 'MOLIDO', 30);
